// Uncomment the following line if you are using Next.js:
// 'use client'
import 'survey-core/defaultV2.min.css';
import { Model } from 'survey-core';
import { Survey } from 'survey-react-ui';
import { BorderlessLight} from "survey-core/themes";
import "survey-core/i18n/spanish";


const surveyJson = {
    "title": "Inventario de Proyecciones Vocacionales",
    "pages": [
        {
            "name": "page1",
            "elements": [
                {"type": "boolean", "name": "q1", "title": "Llevar el control de la tesorería del curso.", "isRequired": true},
                {"type": "boolean", "name": "q2", "title": "Mantener un pequeño huerto en el campo o en el patio de la casa.", "isRequired": true},
                {"type": "boolean", "name": "q3", "title": "Clasificar desechos orgánicos e inorgánicos para poder reciclarlos.", "isRequired": true},
                {"type": "boolean", "name": "q4", "title": "Participar en celebraciones litúrgicas o eucarísticas.", "isRequired": true},
                {"type": "boolean", "name": "q5", "title": "Ser el responsable del orden y la disciplina en el curso.", "isRequired": true},
                {"type": "boolean", "name": "q6", "title": "Poner en práctica reglas del juego limpio (fair play).", "isRequired": true},
                {"type": "boolean", "name": "q7", "title": "Leer diferentes textos de literatura histórica.", "isRequired": true},
                {"type": "boolean", "name": "q8", "title": "Estudiar fórmulas que expliquen leyes como la de gravedad universal y relatividad.", "isRequired": true},
                {"type": "boolean", "name": "q9", "title": "Resolver problemas con regla de tres simple.", "isRequired": true},
                {"type": "boolean", "name": "q10", "title": "Visitar exposiciones de pinturas o esculturas.", "isRequired": true},
                {"type": "boolean", "name": "q11", "title": "Leer una obra literaria aunque no la hayan asignado como tarea de la clase.", "isRequired": true},
                {"type": "boolean", "name": "q12", "title": "Hacer ranking con canciones favoritas.", "isRequired": true},
                {"type": "boolean", "name": "q13", "title": "Estar informado de las últimas tecnologías en materia virtual o computacional.", "isRequired": true},
                {"type": "boolean", "name": "q14", "title": "Desarmar pequeñas máquinas y artefactos electrodomésticos.", "isRequired": true},
                {"type": "boolean", "name": "q15", "title": "Ayudar en el desarrollo de tareas a hermanos o amigos más pequeños.", "isRequired": true},
                {"type": "boolean", "name": "q16", "title": "Recoger materiales que entrega la naturaleza para convertirlos en objetos de arte.", "isRequired": true},
                {"type": "boolean", "name": "q17", "title": "Colaborar con instituciones que entregan algún beneficio social.", "isRequired": true},
                {"type": "boolean", "name": "q18", "title": "Entrevistar a compañeros y amigos.", "isRequired": true},
                {"type": "boolean", "name": "q19", "title": "Hacer cálculos de costo y presupuesto de diferentes productos.", "isRequired": true},
            ]},
            {
            "name": "page2",
                "elements": [
                {"type": "boolean", "name": "q20", "title": "Investigar los momentos oportunos del año para sembrar y plantar.", "isRequired": true},
                {"type": "boolean", "name": "q21", "title": "Utilizar residuos orgánicos para fabricar abonos y fertilizantes.", "isRequired": true},
                {"type": "boolean", "name": "q22", "title": "Formar parte del comité de la pastoral de la escuela o liceo.", "isRequired": true},
                {"type": "boolean", "name": "q23", "title": "Coleccionar réplicas de armas y carros de guerra.", "isRequired": true},
                {"type": "boolean", "name": "q24", "title": "Bañarse o pescar en lagos o riachuelos.", "isRequired": true},
                {"type": "boolean", "name": "q25", "title": "Estudiar la misión que cumplen gremios y partidos políticos.", "isRequired": true},
                {"type": "boolean", "name": "q26", "title": "Construir un muestrario de insectos.", "isRequired": true},
                {"type": "boolean", "name": "q27", "title": "Hacer cálculos de sustracción y división con grandes cifras numéricas.", "isRequired": true},
                {"type": "boolean", "name": "q28", "title": "Revisar la página o el suplemento de Artes en el diario.", "isRequired": true},
                {"type": "boolean", "name": "q29", "title": "Escribir poemas.", "isRequired": true},
                {"type": "boolean", "name": "q30", "title": "Componer pequeñas piezas musicales.", "isRequired": true},
                {"type": "boolean", "name": "q31", "title": "Adquirir el computador o equipo telefónico de última generación.", "isRequired": true},
                {"type": "boolean", "name": "q32", "title": "Hacer funcionar un torno.", "isRequired": true},
                {"type": "boolean", "name": "q33", "title": "Ayudar a mejorar los procesos de lectura y escritura en otras personas.", "isRequired": true},
                {"type": "boolean", "name": "q34", "title": "Trabajar con materiales como arcilla y plasticina.", "isRequired": true},
                {"type": "boolean", "name": "q35", "title": "Integrar equipos de trabajo comunitario.", "isRequired": true},
                {"type": "boolean", "name": "q36", "title": "Ver las noticias en los diarios y la televisión.", "isRequired": true},
                {"type": "boolean", "name": "q37", "title": "Revisar revistas de economía y negocios.", "isRequired": true},
                {"type": "boolean", "name": "q38", "title": "Estudiar sobre los tiempos de preñez de vacas y ovejas.", "isRequired": true},
                {"type": "boolean", "name": "q39", "title": "Aprender formas naturales de control de plagas.", "isRequired": true},
                {"type": "boolean", "name": "q40", "title": "Participar en retiros espirituales.", "isRequired": true},
            ]},
            {
            "name": "page3",
                "elements": [
                {"type": "boolean", "name": "q41", "title": "Analizar la historia de las grandes batallas.", "isRequired": true},
                {"type": "boolean", "name": "q42", "title": "Hacer trote o caminatas por el campo o la ciudad.", "isRequired": true},
                {"type": "boolean", "name": "q43", "title": "Estudiar los principios que definen al hombre como un ser social.", "isRequired": true},
                {"type": "boolean", "name": "q44", "title": "Embalsamar o diseccionar aves y animales menores.", "isRequired": true},
                {"type": "boolean", "name": "q45", "title": "Hacer cálculos porcentuales.", "isRequired": true},
                {"type": "boolean", "name": "q46", "title": "Leer tiras cómicas.", "isRequired": true},
                {"type": "boolean", "name": "q47", "title": "Hacer relatos sobre vivencias personales a compañeros o amigos.", "isRequired": true},
                {"type": "boolean", "name": "q48", "title": "Tocar un instrumento musical.", "isRequired": true},
                {"type": "boolean", "name": "q49", "title": "Procesar textos en Word o PDF.", "isRequired": true},
                {"type": "boolean", "name": "q50", "title": "Estudiar cómo funcionan motores eléctricos y a combustión.", "isRequired": true},
                {"type": "boolean", "name": "q51", "title": "Conformar una pequeña biblioteca con textos que sirvan como textos para enseñar.", "isRequired": true},
                {"type": "boolean", "name": "q52", "title": "Formar figuras con diversos materiales moldeables.", "isRequired": true},
                {"type": "boolean", "name": "q53", "title": "Ser responsable de la representación o protección de otras personas.", "isRequired": true},
                {"type": "boolean", "name": "q54", "title": "Organizar campañas para dar a conocer una nueva idea.", "isRequired": true},
                {"type": "boolean", "name": "q55", "title": "Tener un negocio o iniciar una microempresa.", "isRequired": true},
                {"type": "boolean", "name": "q56", "title": "Aprender de plagas y enfermedades que atacan a plantas y árboles.", "isRequired": true},
                {"type": "boolean", "name": "q57", "title": "Denunciar los efectos nocivos del calentamiento global.", "isRequired": true},
                {"type": "boolean", "name": "q58", "title": "Trabajar en un grupo misionero durante las vacaciones.", "isRequired": true},
                {"type": "boolean", "name": "q59", "title": "Construir legiones o batallones de soldados en miniatura.", "isRequired": true},
                {"type": "boolean", "name": "q60", "title": "Practicar deporte individual o colectivo.", "isRequired": true},
            ]},
            {
            "name": "page4",
                "elements": [
                {"type": "boolean", "name": "q61", "title": "Conocer el funcionamiento de las instituciones más importantes de la sociedad.", "isRequired": true},
                {"type": "boolean", "name": "q62", "title": "Recoger y clasificar rocas y minerales.", "isRequired": true},
                {"type": "boolean", "name": "q63", "title": "Elaborar cuadros estadísticos.", "isRequired": true},
                {"type": "boolean", "name": "q64", "title": "Hacer retratos y caricaturas.", "isRequired": true},
                {"type": "boolean", "name": "q65", "title": "Desarrollar una buena redacción y ortografía.", "isRequired": true},
                {"type": "boolean", "name": "q66", "title": "Integrar un coro.", "isRequired": true},
                {"type": "boolean", "name": "q67", "title": "Hacer registros y cálculos en planillas Excel.", "isRequired": true},
                {"type": "boolean", "name": "q68", "title": "Instalar lámparas y enchufes.", "isRequired": true},
                {"type": "boolean", "name": "q69", "title": "Desarrollar una adecuada capacidad de expresión oral y escrita.", "isRequired": true},
                {"type": "boolean", "name": "q70", "title": "Tejer y trenzar diferentes tipos de fibras vegetales, hilos o lanas.", "isRequired": true},
                {"type": "boolean", "name": "q71", "title": "Defender los derechos de los compañeros de curso.", "isRequired": true},
                {"type": "boolean", "name": "q72", "title": "Apoyar la creación de una revista en la escuela o liceo.", "isRequired": true},
                {"type": "boolean", "name": "q73", "title": "Colaborar con la justa y equitativa distribución de los recursos en la familia.", "isRequired": true},
                {"type": "boolean", "name": "q74", "title": "Proteger la tierra fértil, fuente de alimentos para la población.", "isRequired": true},
                {"type": "boolean", "name": "q75", "title": "Formar parte de una institución que luche por la defensa del medio ambiente.", "isRequired": true},
                {"type": "boolean", "name": "q76", "title": "Comprometerse en campañas para practicar el valor de la caridad.", "isRequired": true},
                {"type": "boolean", "name": "q77", "title": "Formar parte en tropas militares que participan en misiones de paz en países en conflicto.", "isRequired": true},
                {"type": "boolean", "name": "q78", "title": "Cultivar el cuidado y respeto por el propio cuerpo.", "isRequired": true},
                {"type": "boolean", "name": "q79", "title": "Hacer tareas y acciones para la defensa de los derechos humanos.", "isRequired": true},
                {"type": "boolean", "name": "q80", "title": "Desarrollar la capacidad de observación crítica y rigurosa.", "isRequired": true},
            ]},
            {
            "name": "page5",
                "elements": [
                {"type": "boolean", "name": "q81", "title": "Aplicar la matemática para la resolución de problemas de la vida cotidiana.", "isRequired": true},
                {"type": "boolean", "name": "q82", "title": "Fomentar sin límites la capacidad de imaginar.", "isRequired": true},
                {"type": "boolean", "name": "q83", "title": "Practicar una lectura crítica y comprensiva.", "isRequired": true},
                {"type": "boolean", "name": "q84", "title": "Defender el derecho de la libertad para crear.", "isRequired": true},
                {"type": "boolean", "name": "q85", "title": "Usar herramientas virtuales para mejorar la calidad de vida de las personas.", "isRequired": true},
                {"type": "boolean", "name": "q86", "title": "Facilitar la vida de la gente a través del uso de recursos técnicos.", "isRequired": true},
                {"type": "boolean", "name": "q87", "title": "Ayudar a la promoción de la persona humana a través de una educación de calidad.", "isRequired": true},
                {"type": "boolean", "name": "q88", "title": "Aprovechar los recursos del medio natural para desarrollar la capacidad de inventar.", "isRequired": true},
                {"type": "boolean", "name": "q89", "title": "Respetar opiniones diferentes a las propias.", "isRequired": true},
                {"type": "boolean", "name": "q90", "title": "Dar a conocer libremente formas de pensar y sentir.", "isRequired": true},
                {"type": "boolean", "name": "q91", "title": "Preocuparse de las variaciones del Índice de Precios al Consumidor (IPC).", "isRequired": true},
                {"type": "boolean", "name": "q92", "title": "Aprender procedimientos de inseminación artificial.", "isRequired": true},
                {"type": "boolean", "name": "q93", "title": "Protestar por el maltrato animal.", "isRequired": true},
                {"type": "boolean", "name": "q94", "title": "Ayudar en diversas ceremonias religiosas.", "isRequired": true},
                {"type": "boolean", "name": "q95", "title": "Disfrutar de marchas e himnos militares.", "isRequired": true},
                {"type": "boolean", "name": "q96", "title": "Vestir deportivamente con buzo y zapatillas.", "isRequired": true},
                {"type": "boolean", "name": "q97", "title": "Estudiar fenómenos sociales como la cohesión y la movilidad social.", "isRequired": true},
                {"type": "boolean", "name": "q98", "title": "Leer la vida y obra de grandes científicos.", "isRequired": true},
                {"type": "boolean", "name": "q99", "title": "Conocer el uso de tablas trigonométricas.", "isRequired": true},
                {"type": "boolean", "name": "q100", "title": "Pintar pequeños cuadros con témpera o acuarela.", "isRequired": true},
            ]},
            {
            "name": "page6",
                "elements": [
                {"type": "boolean", "name": "q101", "title": "Escribir una bitácora o diario de vida.", "isRequired": true},
                {"type": "boolean", "name": "q102", "title": "Formar parte de una orquesta o grupo musical.", "isRequired": true},
                {"type": "boolean", "name": "q103", "title": "Perfeccionarse en conocimiento de equipos computacionales.", "isRequired": true},
                {"type": "boolean", "name": "q104", "title": "Dibujar planos de máquinas y herramientas.", "isRequired": true},
                {"type": "boolean", "name": "q105", "title": "Aprender a formular objetivos de aprendizaje.", "isRequired": true},
                {"type": "boolean", "name": "q106", "title": "Construir un muro.", "isRequired": true},
                {"type": "boolean", "name": "q107", "title": "Formar parte de la directiva del curso.", "isRequired": true},
                {"type": "boolean", "name": "q108", "title": "Animar un acto o velada.", "isRequired": true},
                {"type": "boolean", "name": "q109", "title": "Conocer las variaciones mensuales de la Unidad de Fomento (UF).", "isRequired": true},
                {"type": "boolean", "name": "q110", "title": "Construir un pozo y usarlo en el regadío de cultivos.", "isRequired": true},
                {"type": "boolean", "name": "q111", "title": "Participar en campañas para impedir contaminación de campos y mares.", "isRequired": true},
                {"type": "boolean", "name": "q112", "title": "Leer la Palabra Sagrada en celebraciones religiosas.", "isRequired": true},
                {"type": "boolean", "name": "q113", "title": "Tomar parte de juegos bélicos.", "isRequired": true},
                {"type": "boolean", "name": "q114", "title": "Hacer gimnasia y ejercicios, periódicamente.", "isRequired": true},
                {"type": "boolean", "name": "q115", "title": "Someter a crítica e interpretar diferentes fuentes y documentos históricos.", "isRequired": true},
                {"type": "boolean", "name": "q116", "title": "Hacer experimentos en laboratorios.", "isRequired": true},
                {"type": "boolean", "name": "q117", "title": "Resolver problemas algebraicos usando la ley de los signos.", "isRequired": true},
                {"type": "boolean", "name": "q118", "title": "Construir collages y otros tipos de expresión plástica.", "isRequired": true},
                {"type": "boolean", "name": "q119", "title": "Participar del taller literario de la escuela o liceo.", "isRequired": true},
                {"type": "boolean", "name": "q120", "title": "Asistir a conciertos de música popular o selecta.", "isRequired": true},
            ]},
            {
            "name": "page7",
                "elements": [
                {"type": "boolean", "name": "q121", "title": "Ser experto en el conocimiento de programas computacionales.", "isRequired": true},
                {"type": "boolean", "name": "q122", "title": "Construir diseños de casas y edificios.", "isRequired": true},
                {"type": "boolean", "name": "q123", "title": "Usar recursos audiovisuales para enseñar una determinada materia.", "isRequired": true},
                {"type": "boolean", "name": "q124", "title": "Hacer joyas con materiales metálicos o vegetales.", "isRequired": true},
                {"type": "boolean", "name": "q125", "title": "Debatir en un foro.", "isRequired": true},
                {"type": "boolean", "name": "q126", "title": "Iniciar estudios de una segunda lengua.", "isRequired": true},
                {"type": "boolean", "name": "q127", "title": "Confeccionar tablas de contabilidad básica con entradas, salidas y saldos.", "isRequired": true},
                {"type": "boolean", "name": "q128", "title": "Investigar acerca de enfermedades y su tratamiento en diferentes animales.", "isRequired": true},
                {"type": "boolean", "name": "q129", "title": "Patrocinar formas de calefacción no contaminante.", "isRequired": true},
                {"type": "boolean", "name": "q130", "title": "Tomar parte en grupos de oración.", "isRequired": true},
                {"type": "boolean", "name": "q131", "title": "Estudiar las fronteras de los países y sus variaciones en el tiempo.", "isRequired": true},
                {"type": "boolean", "name": "q132", "title": "Averiguar sobre índices de resistencia física al ejercicio.", "isRequired": true},
                {"type": "boolean", "name": "q133", "title": "Dialogar sobre género, discriminación e inclusión social.", "isRequired": true},
                {"type": "boolean", "name": "q134", "title": "Comprobar las diferentes etapas del ciclo del agua.", "isRequired": true},
                {"type": "boolean", "name": "q135", "title": "Participar en competencias de sumar y multiplicar grandes cifras numéricas.", "isRequired": true},
                {"type": "boolean", "name": "q136", "title": "Montar una exposición con creaciones plásticas propias.", "isRequired": true},
                {"type": "boolean", "name": "q137", "title": "Publicar pequeñas obras literarias en diarios o revistas.", "isRequired": true},
                {"type": "boolean", "name": "q138", "title": "Identificar tipos o familias de instrumentos en una orquesta.", "isRequired": true},
                {"type": "boolean", "name": "q139", "title": "Instalar nuevos programas en el computador.", "isRequired": true},
                {"type": "boolean", "name": "q140", "title": "Medir, cortar y soldar perfiles metálicos para construir una reja.", "isRequired": true},
            ]},
            {
            "name": "page8",
                "elements": [
                {"type": "boolean", "name": "q141", "title": "Transmitir nuevos conocimientos de una forma clara y motivadora.", "isRequired": true},
                {"type": "boolean", "name": "q142", "title": "Hacer pequeñas esculturas a partir de yeso, metal o madera.", "isRequired": true},
                {"type": "boolean", "name": "q143", "title": "Participar en jornadas para la formación de líderes.", "isRequired": true},
                {"type": "boolean", "name": "q144", "title": "Organizar o participar en un juego de amigo secreto.", "isRequired": true},
                {"type": "boolean", "name": "q145", "title": "Hacer campañas para reunir dinero.", "isRequired": true},
                {"type": "boolean", "name": "q146", "title": "Aprender labores de ordeña en vacas y otros animales.", "isRequired": true},
                {"type": "boolean", "name": "q147", "title": "Defender a la gente que quiere vivir en un ambiente libre de ruidos.", "isRequired": true},
                {"type": "boolean", "name": "q148", "title": "Dirigir actividades de catequesis o escuela dominical.", "isRequired": true},
                {"type": "boolean", "name": "q149", "title": "Desarrollar actitudes de legítima obediencia y lealtad a los superiores.", "isRequired": true},
                {"type": "boolean", "name": "q150", "title": "Seguir con atención grandes acontecimientos deportivos.", "isRequired": true},
                {"type": "boolean", "name": "q151", "title": "Investigar sobre las funciones de los poderes del Estado.", "isRequired": true},
                {"type": "boolean", "name": "q152", "title": "Ensayar las etapas del método científico en experiencias elementales.", "isRequired": true},
                {"type": "boolean", "name": "q153", "title": "Formular ecuaciones de segundo grado.", "isRequired": true},
                {"type": "boolean", "name": "q154", "title": "Tomar clases para aprender técnicas pictóricas.", "isRequired": true},
                {"type": "boolean", "name": "q155", "title": "Perfeccionar técnicas vocales como dicción e impostación de la voz.", "isRequired": true},
                {"type": "boolean", "name": "q156", "title": "Someterse a una prueba de canto para conocer el registro correspondiente.", "isRequired": true},
                {"type": "boolean", "name": "q157", "title": "Configurar equipos computacionales para su adecuado funcionamiento.", "isRequired": true},
                {"type": "boolean", "name": "q158", "title": "Reparar y hacer mantenimiento a maquinaria pesada.", "isRequired": true},
                {"type": "boolean", "name": "q159", "title": "Generar condiciones adecuadas para que las personas aprendan.", "isRequired": true},
            ]},
            {
            "name": "page9",
                "elements": [
                {"type": "boolean", "name": "q160", "title": "Participar en un concurso de construcción de castillos de arena.", "isRequired": true},
                {"type": "boolean", "name": "q161", "title": "Formar parte de un partido político.", "isRequired": true},
                {"type": "boolean", "name": "q162", "title": "Preparar un programa con noticias para dar a conocer al curso.", "isRequired": true},
                {"type": "boolean", "name": "q163", "title": "Ahorrar en una cuenta bancaria parte de la mesada.", "isRequired": true},
                {"type": "boolean", "name": "q164", "title": "Podar parrones y otros árboles frutales.", "isRequired": true},
                {"type": "boolean", "name": "q165", "title": "Impedir el vaciamiento de aguas servidas en diversos cursos de agua.", "isRequired": true},
                {"type": "boolean", "name": "q166", "title": "Participar en el Vía Crucis u otras actividades de Semana Santa.", "isRequired": true},
                {"type": "boolean", "name": "q167", "title": "Leer biografías de grandes estrategas militares.", "isRequired": true},
                {"type": "boolean", "name": "q168", "title": "Revisar el suplemento deportivo de los diarios.", "isRequired": true},
                {"type": "boolean", "name": "q169", "title": "Pertenecer a alguna institución social.", "isRequired": true},
                {"type": "boolean", "name": "q170", "title": "Formular hipótesis frente a fenómenos de la naturaleza.", "isRequired": true},
                {"type": "boolean", "name": "q171", "title": "Calcular problemas de raíz cuadrada.", "isRequired": true},
                {"type": "boolean", "name": "q172", "title": "Conocer la vida y obra de grandes pintores universales.", "isRequired": true},
                {"type": "boolean", "name": "q173", "title": "Representar un papel en una obra de teatro.", "isRequired": true},
                {"type": "boolean", "name": "q174", "title": "Leer partituras musicales.", "isRequired": true},
                {"type": "boolean", "name": "q175", "title": "Participar en redes computacionales para conseguir nuevos amigos.", "isRequired": true},
                {"type": "boolean", "name": "q176", "title": "Manejar un camión de faenas mineras.", "isRequired": true},
                {"type": "boolean", "name": "q177", "title": "Poner nota a trabajos de compañeros y amigos.", "isRequired": true},
                {"type": "boolean", "name": "q178", "title": "Aprender a hacer tatuajes.", "isRequired": true},
                {"type": "boolean", "name": "q179", "title": "Integrar una lista para ocupar un cargo público.", "isRequired": true},
                {"type": "boolean", "name": "q180", "title": "Formar un equipo para crear una radio en la escuela o colegio.", "isRequired": true}
            ]
        }
    ]
};

function App() {
    const survey = new Model(surveyJson);
    survey.locale = "es";
    survey.applyTheme(BorderlessLight)
    return <Survey model={survey} />;
}

export default App;
